format = """
$nix_shell\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character\
"""

right_format		= """
$status\
"""

[directory]
truncation_length	= 9
style				= "blue"
repo_root_style		= "yellow"
truncate_to_repo	= false
read_only			= " "

[username]
format				= "[$user]($style)@"
show_always			= false

[hostname]
format				= "[$hostname]($style) "
ssh_only			= true
trim_at				= '.'

[character]
success_symbol		= "[❯](purple)"
error_symbol		= "[❯](red)"
vicmd_symbol		= "[❮](green)"

[nix_shell]
disabled			= false
format				= '[(\($name\))](bold yellow) '

[git_branch]
format				= '[$symbol$branch]($style) '
style				= 'bold white'
symbol				= " "

[git_status]
format				= "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style				= "cyan"
ignore_submodules	= false

conflicted			= '='
ahead				= '⇡'
behind				= '⇣'
diverged			= '⇕'
up_to_date			= '' 
untracked			= '?'
stashed				= '\$'
modified			= '!'
staged				= '+'
renamed				= '»'
deleted				= '✘'

[git_state]
format				= '\([$state( $progress_current/$progress_total)]($style)\) '
style				= "white"

[cmd_duration]
format				= "[$duration]($style) "
style				= "yellow"

[status]
format				= ' [$status]($style) '
disabled			= false

